// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zydgxkubvlaozhzsdctj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5ZGd4a3Vidmxhb3poenNkY3RqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxODU2MjgsImV4cCI6MjA2Nzc2MTYyOH0.1-dAbqzVqvmnBmd8bFTuLBK00gKBDZEtIbg6TkPrhE4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});